sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: (your password)
  file:
    upload-path: D:/Java/sky-take-out/upload/
  redis:
    host: (your redis host)
    port: (your redis port)
    password: (your redis password)
    database: (your redis database)
  wechat:
    appid: (your wechat appid)
    secret: (your wechat secret)